import React from "react";
import DataTable from "./lib";

const App = () => {
  const columns = [
    {
      name: "First Name",
      selector: "firstName",
      sortable: true,
    },
    {
      name: "Last Name",
      selector: "lastName",
      sortable: true,
    },
    {
      name: "Start Date",
      selector: "startDate",
      sortable: true,
    },
    {
      name: "Department",
      selector: "department",
      sortable: true,
    },
    {
      name: "Date of Birth",
      selector: "dateOfBirth",
      sortable: true,
    },
    {
      name: "Street",
      selector: "street",
      sortable: true,
    },
    {
      name: "City",
      selector: "city",
      sortable: true,
    },
    {
      name: "State",
      selector: "state",
      sortable: true,
    },
    {
      name: "Zip Code",
      selector: "zipCode",
      sortable: true,
    },
  ];

  const data = [
    {
      id: 1,
      firstName: "Christina",
      lastName: "Leon",
      dateOfBirth: "1983-04-23",
      startDate: "2015-03-01",
      street: "3247 Hampton Meadows",
      city: "Haverhill",
      state: "MA",
      zipCode: "01830",
      department: "Sales",
    },
    {
      id: 2,
      firstName: "Richard",
      lastName: "Castillo",
      dateOfBirth: "1952-11-22",
      startDate: "2013-01-25",
      street: "4599 Hill Street",
      city: "Toledo",
      state: "OH",
      zipCode: "43609",
      department: "Marketing",
    },
    {
      id: 3,
      firstName: "Carl",
      lastName: "Sanders",
      dateOfBirth: "1953-10-20",
      startDate: "2015-11-02",
      street: "4225 Froe Street",
      city: "Wheeling",
      state: "WV",
      zipCode: "26003",
      department: "Engineering",
    },
    {
      id: 4,
      firstName: "Ethel",
      lastName: "Workman",
      dateOfBirth: "1988-06-20",
      startDate: "2014-03-17",
      street: "1622 Hummingbird Way",
      city: "Charlestown",
      state: "MA",
      zipCode: "02129",
      department: "Human Resources",
    },
    {
      id: 5,
      firstName: "John",
      lastName: "Roddy",
      dateOfBirth: "1976-03-01",
      startDate: "2014-04-03",
      street: "2737 Poe Lane",
      city: "Shawnee",
      state: "KS",
      zipCode: "66214",
      department: "Legal",
    },
    {
      id: 6,
      firstName: "Andrew",
      lastName: "Craig",
      dateOfBirth: "1962-06-27",
      startDate: "2015-03-24",
      street: "4293 John Daniel Drive",
      city: "Cape Girardeau",
      state: "MO",
      zipCode: "63701",
      department: "Sales",
    },
    {
      id: 7,
      firstName: "Rafael",
      lastName: "Strain",
      dateOfBirth: "1995-12-06",
      startDate: "2014-06-05",
      street: "4204 Owagner Lane",
      city: "Burlen",
      state: "WA",
      zipCode: "98168",
      department: "Marketing",
    },
    {
      id: 8,
      firstName: "Patricia",
      lastName: "Jimenez",
      dateOfBirth: "1987-07-28",
      startDate: "2014-01-06",
      street: "1775 Orphan Road",
      city: "Buffalo",
      state: "NY",
      zipCode: "14202",
      department: "Engineering",
    },
    {
      id: 9,
      firstName: "Lori",
      lastName: "Branch",
      dateOfBirth: "1989-09-20",
      startDate: "2014-04-22",
      street: "3879 Victoria Street",
      city: "Baton Rouge",
      state: "LA",
      zipCode: "70811",
      department: "Human Resources",
    },
    {
      id: 10,
      firstName: "Clara",
      lastName: "Keltner",
      dateOfBirth: "1966-04-20",
      startDate: "2016-09-01",
      street: "4291 Heritage Road",
      city: "Fresno",
      state: "CA",
      zipCode: "93721",
      department: "Legal",
    },
    {
      id: 11,
      firstName: "Maria",
      lastName: "Kingery",
      dateOfBirth: "1997-05-04",
      startDate: "2014-05-17",
      street: "791 Sampson Street",
      city: "Denver",
      state: "CO",
      zipCode: "80202",
      department: "Sales",
    },
    {
      id: 12,
      firstName: "Joe",
      lastName: "Satterfield",
      dateOfBirth: "1983-08-03",
      startDate: "2013-04-12",
      street: "2296 Courtright Street",
      city: "West Fargo",
      state: "ND",
      zipCode: "58078",
      department: "Marketing",
    },
    {
      id: 13,
      firstName: "Alvin",
      lastName: "Barrera",
      dateOfBirth: "1958-06-21",
      startDate: "2014-04-29",
      street: "3988 Green Acres Road",
      city: "Rocky Mount",
      state: "NC",
      zipCode: "27804",
      department: "Engineering",
    },
    {
      id: 14,
      firstName: "Vernon",
      lastName: "Crary",
      dateOfBirth: "1987-08-14",
      startDate: "2015-11-22",
      street: "2757 Jody Road",
      city: "Ardmore",
      state: "PA",
      zipCode: "19003",
      department: "Human Resources",
    },
    {
      id: 15,
      firstName: "Christine",
      lastName: "Brunetti",
      dateOfBirth: "1985-03-19",
      startDate: "2013-02-15",
      street: "21 Alfred Drive",
      city: "Bronx",
      state: "NY",
      zipCode: "10467",
      department: "Legal",
    },
    {
      id: 16,
      firstName: "Rhonda",
      lastName: "Mills",
      dateOfBirth: "1983-03-11",
      startDate: "2013-08-20",
      street: "2247 American Drive",
      city: "Tallahassee",
      state: "FL",
      zipCode: "32312",
      department: "Sales",
    },
  ];

  return (
    <DataTable
      columns={columns}
      data={data}
      headerColor={"#123456"}
      rowColor={"#456789"}
      alternateRowColor={"#789ABC"}
      hoverRowColor={"#ABCDEF"}
    />
  );
};

export default App;
